title: "Храм во имя свт. Феофана Затворника (п. Магистральный)"
description: "Официальный сайт"
baseurl: ""  
url: "https://magistralfeofana.github.io"

theme: minima  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
sass:
  sass_dir: _sass
  style: compressed

timezone: Asia/Irkutsk
encoding: utf-8