title: "Магистраль Феофана"
description: "Официальный сайт"
baseurl: ""  # Если сайт username.github.io, оставь пустым
url: "https://username.github.io"  # Замени на свой URL

theme: minima  # Можно выбрать другую тему
plugins:
  - jekyll-feed
  - jekyll-seo-tag
